version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
    
  [[blocks.segments]]
    type = 'text'
    foreground = 'p:lavender'
    background = 'transparent'
    template = '{{.UserName}}'
  [[blocks.segments]]
    type = 'text'
    foreground = 'p:text'
    background = 'transparent'
    template = '@'
  [[blocks.segments]]
    type = 'text'
    foreground = 'p:sapphire'
    background = 'transparent'
    template = '{{.HostName}}'
  [[blocks.segments]]
    type = 'text'
    foreground = 'p:text'
    background = 'transparent'
    template = ':'
  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:mauve"
    background = 'transparent'
    template = "{{ .Path }}"
    
    [blocks.segments.properties]
        style = 'full'
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:peach'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}↓{{ end }}{{ if gt .Ahead 0 }}↑{{ end }}</>'
    
    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 3000


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    background = 'transparent'
    foreground_templates = [
        "{{if gt .Code 0}}p:red{{end}}",
        "{{if eq .Code 0}}p:green{{end}}"
    ]
    template = 'λ'

[secondary_prompt]
  foreground = 'p:text'
  background = 'transparent'
  template = '> '
